### ISSUE TITLE
Build resctl-demo when an upstream version is released rather than on a schedule

### ISSUE THREAD

**Issue by obbardc** [iocost-benchmark/iocost-benchmarks-ci#1]
Currently we build `resctl-demo` every-week on a Monday early-morning (or a manual build can be initiated by pressing `Actions > Build resctl-demo > Run workflow`).

Rebuilding things which haven't changed is a waste of CI resources and there is a cadence if a new version of `resctl-demo` has been released.

We should probably change this to check for changes to upstream and only re-build when needed.

**Comment by santoshmahto7** [comment]
There is difficulty in implementing this without infecting resctl-demo CI.
Github actions doesn't have facility to watch for changes in external repository and then trigger workflow. 

The only way this is done is  by sending _repository_dispatch_ event from upstream repo to listening repo.
i.e resctl-demo repo CI job will send repository_dispatch event and iocost-benchmark-ci will listen for this event and trigger workflow when this event is sent by upstream resctl-demo.
see discussion here: https://github.com/orgs/community/discussions/26323

So we would need to add code in resctl-demo workflow to emit repository_dispatch event when new release is made.
I ain't sure if this is acceptable here( modifying resctl-demo workflow and adding other project information) 
@saravan2 @htejun

**Comment by obbardc** [comment]
Could the checking of a new tag be done in a nightly job ?

**Comment by santoshmahto7** [comment]
PR is merged so we can close this issue:
https://github.com/iocost-benchmark/iocost-benchmarks-ci/pull/17
